newtodoproject/newtodoapp/urls.py
from . import views
from django.urls import path,include

app_name='newtodoapp'
urlpatterns = [

    path('',views.add,name='add'),
   # path('details',views.details,name='details')
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.TaskListView.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/', views.TaskDetailView.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.TaskUpdateView.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.TaskDeleteView.as_view(), name='cbvdelete'),
]

newtodoproject/newtodoproject/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("newtodoapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

newtodoproject/newtodoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()

    def __str__(self):
       return self.name

newtodoproject/newtodoapp/forms.py
from django import forms
from .models import Task

class newtodoForm(forms.ModelForm):
    class Meta:
      model=Task
      fields=['name','priority','date']

newtodoproject/newtodoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import Task
from . forms import newtodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView


# Create your views here.
class TaskListView(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task1'
class TaskDetailView(DetailView):
     model = Task
     template_name = 'detail.html'
     context_object_name = 'task'
class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','date')
    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})
class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('cbvhome')


def add(request):
    task1=Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task1':task1})
#def details(request):
 #   task=Task.objects.all()
 #   return render(request,'detail.html',{'task':task})

def delete(request,taskid):
   task=Task.objects.get(id=taskid)
   if request.method=='POST':
     task.delete()
     return redirect('/')
   return render(request,'delete.html')


def update(request,id):
    task=Task.objects.get(id=id)
    f=newtodoForm(request.POST or None, request.FILES,instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'edit.html',{'f':f,'task':task})

newtodoproject/newtodoapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

newtodoproject/newtodoapp/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
{% csrf_token %}
  <p> Are you sure this task is done?</p>
  <button type="submit">Confirm</button>
</form>
{% endblock %}

newtodoproject/newtodoapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}
 <div class="shadow">
     <div class="card body">
         <h5 class="card-title">{{task.name}} </h5>
         <p><b>{{task.priority}}</b></p>
         <p><b>{{task.date}}</b></p>
         <a class="btn btn-danger" href="{% url 'newtodoapp:delete' task.id %}">Delete</a>
         <a class="btn btn-warning" href="{% url 'newtodoapp:update' task.id %}">Update</a>
     </div>
 </div>
{% endblock %}

newtodoproject/newtodoapp/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{f.as_p}}
  <button type="submit">Confirm</button>

</form>
{% endblock %}

newtodoproject/newtodoapp/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1> ToDo</h1>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
         <form method="post" class="p-3 shadow">
          {% csrf_token %}
            <div class="form-group">
             <input type="text" class="form-control" name="task" placeholder="taskname">
            </div>
             <div class="form-group">
             <input type="text" class="form-control" name="priority" placeholder="Enter your priority">
             </div>
              <div class="form-group">
             <input type="date" class="form-control" name="date" placeholder="Enter date">
             </div>

                 <input type="submit" class="btn btn-success">
         </form>


        </div>
        <div class="col-md-6">
            <h4> Task to be completed</h4>
            {% for i in task1 %}
            <div class="shadow">
                <div class="card body">
                    <h5 class="card-title">{{i.name}} </h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'newtodoapp:delete' i.id %}">Delete</a>
                    <a class="btn btn-warning" href="{% url 'newtodoapp:update' i.id %}">Update</a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>

    </div>
</div>

{% endblock %}

newtodoproject/newtodoapp/templates/update.html
<div class="card">
  <div class="card-header">
    <div class="card-title">
      Task Update
    </div>
    <div class="card-body">
      <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">Confirm</button>

      </form>
    </div>
  </div>
</div>